# Change these first
owner: pinapelz # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Moekyun Service (Social, Gitea)
    url: https://social.moekyun.me/api/server-info
  - name: Patchwork Archive
    url: https://archive.pinapelz.moe/api/database/status
  - name: Patchwork Radio
    url: https://a4.asurahosting.com/api/nowplaying_static/patchworkarchive.json
  - name: Moekyun Link Shortener
    url: https://link.moekyun.me/
  - name: PhaseTracker
    url: https://api.phase-tracker.com/api/channel/Erina%20Makina
  - name: VTuber Captcha
    url: https://vtuber-captcha.vercel.app/api/affiliation/Hololive
  - name: Leciel (Tachi)
    url: https://leciel.pinapelz.com/api/v1/config
  - name: Leciel ~Pharia~ (eAmuse)
    url: https://pharia.pinapelz.com
  - name: Leciel ~Quna~ (ALL.Net)
    url: https://kanui.pinapelz.com
  
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.moekyun.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Moekyun Service Status
  introTitle: "Uptime and Status of all ~Moekyun Services~"
  introMessage: "Providing only the most moe of web services. Please report all issues to [GitHub](https://github.com/pinapelz/upptime)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
